apiVersion: v1
kind: Service
metadata:
  name: hello-api-service
spec:
  selector:
    app: hello-api
  type: LoadBalancer
  ports:
    - name: hello-api-port
      port: 8080
      targetPort: hello-api-svc
